# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aquarium' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aquarium
  pod 'ImagePicker'

  target 'aquariumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aquariumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
